CREATE DATABASE BTL2;
GO
USE BTL2;
GO

CREATE TABLE ORGANIZATION (
    OrganizationID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Address NVARCHAR(255),
    Phone NVARCHAR(20),
    Email NVARCHAR(100) UNIQUE,
    TaxID NVARCHAR(50),
    Website NVARCHAR(100),
    CONSTRAINT CHK_Organization_PhoneFormat CHECK (Phone LIKE '[0-9]%')
);

CREATE TABLE USER_ACCOUNT (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    UserPassword NVARCHAR(100) NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M','F')),
    DateOfBirth DATE NOT NULL,
    UserAge INT,
    Join_Date DATE DEFAULT GETDATE(),
    Status NVARCHAR(50),
    OrganizationID INT NULL,
    FOREIGN KEY (OrganizationID) REFERENCES ORGANIZATION(OrganizationID)
);


CREATE TABLE SSO (
    SSO_ID INT IDENTITY PRIMARY KEY,
    Provider NVARCHAR(50) NOT NULL,
    SaveIn NVARCHAR(100),
    UserID INT UNIQUE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);


CREATE TABLE STUDENT (
    UserID INT PRIMARY KEY,
    Major NVARCHAR(100),
    Education_Level NVARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

CREATE TABLE INSTRUCTOR (
    UserID INT PRIMARY KEY,
    Expertise NVARCHAR(200),
    Bio NVARCHAR(MAX),
    Qualification NVARCHAR(200),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

CREATE TABLE ADMIN (
    UserID INT PRIMARY KEY,
    Role NVARCHAR(50),
    Permission_Level NVARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);


CREATE TABLE GUARDIAN (
    GuardianID INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE,
    Phone NVARCHAR(20)
);


CREATE TABLE COURSE (
    CourseID INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    Category NVARCHAR(100),
    Language NVARCHAR(50),
    Price DECIMAL(10,2) CHECK (Price >= 0),
    Duration INT CHECK (Duration > 0),
    Create_Date DATE DEFAULT GETDATE(),
    InstructorID INT NOT NULL,
    FOREIGN KEY (InstructorID) REFERENCES INSTRUCTOR(UserID)
);


CREATE TABLE LESSON (
    LessonID INT IDENTITY PRIMARY KEY,
    Lesson_No INT NOT NULL CHECK (Lesson_No > 0),
    Process_Pct FLOAT CHECK (Process_Pct BETWEEN 0 AND 100),
    CourseID INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);


CREATE TABLE CONTENT_ITEM (
    ContentID INT IDENTITY PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    Date_Create DATE DEFAULT GETDATE(),
    LessonID INT NOT NULL,
    FOREIGN KEY (LessonID) REFERENCES LESSON(LessonID)
);

CREATE TABLE VIDEO (
    ContentID INT PRIMARY KEY,
    Duration INT CHECK (Duration > 0),
    Resolution NVARCHAR(50),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);

CREATE TABLE QUIZ (
    ContentID INT PRIMARY KEY,
    Description NVARCHAR(MAX),
    Date_Upload DATE DEFAULT GETDATE(),
    Number_Questions INT CHECK (Number_Questions > 0),
    PassingScore FLOAT CHECK (PassingScore BETWEEN 0 AND 100),
    MaxAttempts INT CHECK (MaxAttempts > 0),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);

CREATE TABLE DOCUMENT (
    ContentID INT PRIMARY KEY,
    FileURL NVARCHAR(255),
    Format NVARCHAR(20),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);


CREATE TABLE CERTIFICATE (
    CertificateID INT IDENTITY PRIMARY KEY,
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    ReceiveDate DATE DEFAULT GETDATE(),
    UNIQUE(StudentID, CourseID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);


CREATE TABLE FORUM (
    ForumID INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    Create_Date DATE DEFAULT GETDATE(),
    CreatorID INT NOT NULL,
    CourseID INT UNIQUE NOT NULL,
    FOREIGN KEY (CreatorID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);


CREATE TABLE POST (
    PostID INT IDENTITY PRIMARY KEY,
    ForumID INT NOT NULL,
    AuthorID INT NOT NULL,
    Content NVARCHAR(MAX),
    Create_Date DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID),
    FOREIGN KEY (AuthorID) REFERENCES USER_ACCOUNT(UserID)
);


CREATE TABLE USER_ORGANIZATION (
    UserID INT NOT NULL,
    OrganizationID INT NOT NULL,
    Join_Date DATE DEFAULT GETDATE(),
    Status NVARCHAR(50),
    PRIMARY KEY (UserID, OrganizationID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (OrganizationID) REFERENCES ORGANIZATION(OrganizationID)
);


CREATE TABLE ADMIN_SUPERVISE (
    SupervisorID INT NOT NULL,
    SubAdminID INT NOT NULL,
    Assign_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (SupervisorID, SubAdminID),
    FOREIGN KEY (SupervisorID) REFERENCES ADMIN(UserID),
    FOREIGN KEY (SubAdminID) REFERENCES ADMIN(UserID)
);


CREATE TABLE STUDENT_GUARDIAN (
    StudentID INT NOT NULL,
    GuardianID INT NOT NULL,
    PRIMARY KEY (StudentID, GuardianID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (GuardianID) REFERENCES GUARDIAN(GuardianID)
);


CREATE TABLE STUDENT_COURSE (
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    Payment DECIMAL(10,2),
    Progress FLOAT CHECK (Progress BETWEEN 0 AND 100),
    PRIMARY KEY (StudentID, CourseID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);


CREATE TABLE QUIZ_RESULT (
    StudentID INT NOT NULL,
    ContentID INT NOT NULL,
    AttemptCount INT CHECK (AttemptCount >= 1),
    Score FLOAT CHECK (Score BETWEEN 0 AND 100),
    PRIMARY KEY (StudentID, ContentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (ContentID) REFERENCES QUIZ(ContentID)
);


CREATE TABLE DOCUMENT_DOWNLOAD (
    StudentID INT NOT NULL,
    ContentID INT NOT NULL,
    DownloadDate DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (StudentID, ContentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (ContentID) REFERENCES DOCUMENT(ContentID)
);


CREATE TABLE USER_FORUM_JOIN (
    UserID INT NOT NULL,
    ForumID INT NOT NULL,
    Role NVARCHAR(50),
    Permission_Level NVARCHAR(50),
    Join_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (UserID, ForumID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID)
);


CREATE TABLE USER_FORUM_MOD (
    UserID INT NOT NULL,
    ForumID INT NOT NULL,
    Role NVARCHAR(50),
    Assign_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (UserID, ForumID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID)
);


