CREATE DATABASE BTL2_DATABASE;
USE BTL2_DATABASE;

--Ph?n 1
--1. USER TABLE & ROLE SYSTEM
--1
CREATE TABLE ORGANIZATION (
    OrganizationID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Address NVARCHAR(255),
    Phone NVARCHAR(20),
    Email NVARCHAR(100),
    TaxID NVARCHAR(50),
    Website NVARCHAR(100),
    CONSTRAINT UQ_Organization_Email UNIQUE (Email),
    CONSTRAINT CHK_Organization_PhoneFormat CHECK (Phone LIKE '[0-9]%')
);

-- 2. USER_ACCOUNT
CREATE TABLE USER_ACCOUNT (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    UserPassword NVARCHAR(100) NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M','F')),
    DateOfBirth DATE NOT NULL,
    UserAge INT,  -- s? ðý?c tính b?ng trigger
    Join_Date DATE DEFAULT GETDATE(),
    Status NVARCHAR(50),
    OrganizationID INT NULL,
    FOREIGN KEY (OrganizationID) REFERENCES ORGANIZATION(OrganizationID)
);
GO

-- 3. SSO
CREATE TABLE SSO (
    SSO_ID INT IDENTITY(1,1) PRIMARY KEY,
    Provider NVARCHAR(50) NOT NULL,
    SaveIn NVARCHAR(100),
    UserID INT UNIQUE NOT NULL,
    CONSTRAINT FK_SSO_User FOREIGN KEY (UserID)
        REFERENCES USER_ACCOUNT(UserID)
);

-- 4. USER SUBCLASSES
CREATE TABLE STUDENT (
    UserID INT PRIMARY KEY,
    Major NVARCHAR(100),
    Education_Level NVARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

--5
CREATE TABLE INSTRUCTOR (
    UserID INT PRIMARY KEY,
    Expertise NVARCHAR(200),
    Bio NVARCHAR(MAX),
    Qualification NVARCHAR(200),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

--6
CREATE TABLE ADMIN (
    UserID INT PRIMARY KEY,
    Role NVARCHAR(50),
    Permission_Level NVARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

-- 7. GUARDIAN
CREATE TABLE GUARDIAN (
    GuardianID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100),
    Phone NVARCHAR(20),
    CONSTRAINT UQ_Guardian_Email UNIQUE (Email)
);

-- 8. COURSE SYSTEM
CREATE TABLE COURSE (
    CourseID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    Category NVARCHAR(100),
    Language NVARCHAR(50),
    Price DECIMAL(10,2) CHECK (Price >= 0),
    Duration INT CHECK (Duration > 0),
    Create_Date DATE DEFAULT GETDATE(),
    InstructorID INT NOT NULL,
    FOREIGN KEY (InstructorID) REFERENCES INSTRUCTOR(UserID)
);

--9
CREATE TABLE LESSON (
    LessonID INT IDENTITY(1,1) PRIMARY KEY,
    Lesson_No INT NOT NULL CHECK (Lesson_No > 0),
    Process_Pct FLOAT CHECK (Process_Pct BETWEEN 0 AND 100),
    CourseID INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

--10
CREATE TABLE CONTENT_ITEM (
    ContentID INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    Date_Create DATE DEFAULT GETDATE(),
    LessonID INT NOT NULL,
    FOREIGN KEY (LessonID) REFERENCES LESSON(LessonID)
);

--11
CREATE TABLE VIDEO (
    ContentID INT PRIMARY KEY,
    Duration INT CHECK (Duration > 0),
    Resolution NVARCHAR(50),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);

--12
CREATE TABLE QUIZZ (
    ContentID INT PRIMARY KEY,
    NumberOfQuestion INT CHECK (NumberOfQuestion > 0),
    PassingScore FLOAT CHECK (PassingScore BETWEEN 0 AND 100),
    MaxAttempts INT CHECK (MaxAttempts > 0),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);

--13
CREATE TABLE DOCUMENT (
    ContentID INT PRIMARY KEY,
    FileURL NVARCHAR(255),
    Format NVARCHAR(20),
    FOREIGN KEY (ContentID) REFERENCES CONTENT_ITEM(ContentID)
);

--14
CREATE TABLE CERTIFICATE (
    CertificateID INT IDENTITY(1,1) PRIMARY KEY,
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    ReceiveDate DATE DEFAULT GETDATE(),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

-- 15. FORUM & POST
CREATE TABLE FORUM (
    ForumID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX),
    Create_Date DATE DEFAULT GETDATE(),
    CreatorID INT NOT NULL,
    FOREIGN KEY (CreatorID) REFERENCES USER_ACCOUNT(UserID)
);

--16
CREATE TABLE POST (
    PostID INT IDENTITY(1,1) PRIMARY KEY,
    ForumID INT NOT NULL,
    AuthorID INT NOT NULL,
    Content NVARCHAR(MAX),
    Create_Date DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID),
    FOREIGN KEY (AuthorID) REFERENCES USER_ACCOUNT(UserID)
);

-- ==============================================
-- PH?N 2??: RELATION (N:M) TABLES
-- ==============================================

-- USER – ORGANIZATION (Has_Member)
--17
CREATE TABLE USER_ORGANIZATION (
    UserID INT NOT NULL,
    OrganizationID INT NOT NULL,
    Join_Date DATE DEFAULT GETDATE(),
    Status NVARCHAR(50),
    PRIMARY KEY (UserID, OrganizationID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (OrganizationID) REFERENCES ORGANIZATION(OrganizationID)
);

-- ADMIN – STUDENT (Supervise)
--18
CREATE TABLE ADMIN_SUPERVISE (
    AdminID INT NOT NULL,
    StudentID INT NOT NULL,
    Assign_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (AdminID, StudentID),
    FOREIGN KEY (AdminID) REFERENCES ADMIN(UserID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID)
);

-- STUDENT – GUARDIAN
--19
CREATE TABLE STUDENT_GUARDIAN (
    StudentID INT NOT NULL,
    GuardianID INT NOT NULL,
    PRIMARY KEY (StudentID, GuardianID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (GuardianID) REFERENCES GUARDIAN(GuardianID)
);

-- STUDENT – COURSE
--20
CREATE TABLE STUDENT_COURSE (
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    Payment DECIMAL(10,2),
    Progress FLOAT CHECK (Progress BETWEEN 0 AND 100),
    PRIMARY KEY (StudentID, CourseID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

-- STUDENT – QUIZZ
--21
CREATE TABLE QUIZZ_RESULT (
    StudentID INT NOT NULL,
    ContentID INT NOT NULL,
    AttemptCount INT CHECK (AttemptCount >= 1),
    Score FLOAT CHECK (Score BETWEEN 0 AND 100),
    PRIMARY KEY (StudentID, ContentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (ContentID) REFERENCES QUIZZ(ContentID)
);

-- STUDENT – DOCUMENT
--22
CREATE TABLE DOCUMENT_DOWNLOAD (
    StudentID INT NOT NULL,
    ContentID INT NOT NULL,
    DownloadDate DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (StudentID, ContentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(UserID),
    FOREIGN KEY (ContentID) REFERENCES DOCUMENT(ContentID)
);

-- USER – FORUM (Joins)
--23
CREATE TABLE USER_FORUM_JOIN (
    UserID INT NOT NULL,
    ForumID INT NOT NULL,
    Role NVARCHAR(50),
    Permission_Level NVARCHAR(50),
    Join_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (UserID, ForumID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID)
);

-- USER – FORUM (Moderates)
--24
CREATE TABLE USER_FORUM_MOD (
    UserID INT NOT NULL,
    ForumID INT NOT NULL,
    Role NVARCHAR(50),
    Assign_Date DATE DEFAULT GETDATE(),
    PRIMARY KEY (UserID, ForumID),
    FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
    FOREIGN KEY (ForumID) REFERENCES FORUM(ForumID)
);


